// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Collections.Generic;
using System.Linq;

namespace CommentTest
{
	public partial class ImageInfoVC : NSViewController
	{
		List<NSUrl> _items;

		public ImageInfoVC (IntPtr handle) : base (handle)
		{
		}

		public void SetData (List<NSUrl> items)
		{
			_items = items;
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			if (_items != null && _items.Count == 1) {
				var comm = FileHelper.GetImageComment (_items.First ());
				TxtComment.Value = comm;
			}
		}

		partial void SaveClicked (NSObject sender)
		{
			if (_items != null && _items.Count > 0) {

				var newComm = TxtComment.Value;

				foreach (var item in _items) {
					FileHelper.SetImageComment (item, newComm);
				}
			}

			this.View.Window?.Close ();
		}
	}
}
